# Copyright (C) 2024-2025 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

ARG UBI_VERSION=9
FROM quay.io/triton-dev-containers/ubi${UBI_VERSION}-base:latest AS base

ARG INSTALL_LLVM=skip
ARG INSTALL_TORCH=pip
ARG INSTALL_TRITON=source
ARG INSTALL_VLLM=skip

USER 0

ARG ROCM_VERSION=6.4.4
ARG AMDGPU_INSTALL_URL=https://repo.radeon.com/amdgpu-install/${ROCM_VERSION}/rhel

# Install the AMD ROCm Repo and GPG key
RUN source /etc/os-release && \
    AMDGPU_INSTALL_RPM=$(curl -s ${AMDGPU_INSTALL_URL}/${VERSION_ID}/ | grep href | sed -e 's/.*href="//' -e 's/".*//' |grep "amdgpu-install-${ROCM_VERSION%.*}.*${VERSION_ID%.*}.noarch.rpm") && \
    dnf -y install ${AMDGPU_INSTALL_URL}/${VERSION_ID}/${AMDGPU_INSTALL_RPM}

# Install the ROCm rpms
RUN dnf -y install --nodocs --setopt=install_weak_deps=False \
    amd-smi-lib \
    miopen-hip \
    rocm-core \
    rocm-hip-libraries \
    rocminfo && \
    dnf clean all && rm -rf /var/cache/yum

# Set environment variables for ROCm
ENV ROCM_VERSION=$ROCM_VERSION \
    ROCM_PATH=/opt/rocm \
    LD_LIBRARY_PATH=/usr/lib64:/usr/lib:/opt/rocm/lib:/opt/rocm/llvm/lib \
    PATH=/opt/rocm/bin:/opt/rocm/llvm/bin:$PATH \
    INSTALL_TORCH=$INSTALL_TORCH \
    INSTALL_TRITON=$INSTALL_TRITON \
    INSTALL_VLLM=$INSTALL_VLLM

COPY hack/triton-gpu-check.py triton-gpu-check.py
COPY examples/triton-vector-add-rocm.py triton-vector-add-rocm.py
COPY examples/flash_attention_demo.ipynb flash_attention_demo.ipynb

COPY scripts/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["tail", "-f", "/dev/null"]
