# Copyright (C) 2024-2025 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

ARG UBI_VERSION=9
FROM quay.io/triton-dev-containers/ubi${UBI_VERSION}-base:latest AS base

ARG CUDA_VERSION=12-9

ARG INSTALL_LLVM=skip
ARG INSTALL_TORCH=pip
ARG INSTALL_TRITON=source
ARG INSTALL_VLLM=skip

USER 0

RUN dnf -y update && \
    dnf -y install libglvnd-opengl libxkbfile \
    qt5-qtwayland xcb-util-cursor && \
    dnf clean all && rm -rf /var/cache/dnf

ENV CUDA_VERSION=$CUDA_VERSION \
    INSTALL_LLVM=$INSTALL_LLVM \
    INSTALL_TORCH=$INSTALL_TORCH \
    INSTALL_TRITON=$INSTALL_TRITON \
    INSTALL_VLLM=$INSTALL_VLLM

COPY examples/flash_attention_demo.ipynb flash_attention_demo.ipynb

COPY scripts/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["tail", "-f", "/dev/null"]
